name: Build Unity Project

on: [workflow_dispatch]

jobs:
  build-unity-project-standalone:
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, StandaloneOSX, StandaloneLinux64]
    name: Build Unity Project ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-GameFeelLab-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-GameFeelLab-
            Library-
      - name: Build Unity ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: CliffLeeCL.ProjectBuilder.BuildProject
          customParameters: -outputPath artifacts -defineSymbolConfig Debug
      - name: Upload Unity Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameFeelLab-${{ matrix.targetPlatform }}
          path: artifacts

  build-unity-project-webgl:
    name: Build Unity Project WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-GameFeelLab-WebGL
          restore-keys: |
            Library-GameFeelLab-
            Library-
      - name: Build Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: CliffLeeCL.ProjectBuilder.BuildProject
          customParameters: -outputPath artifacts -defineSymbolConfig Debug
      - name: Upload Unity Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameFeelLab-WebGL
          path: artifacts