name: Build Unity Project

on: [push, workflow_dispatch]

jobs:
  build-unity-project:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Build Unity Windows 64-bit
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
