name: Test Unity Project

on: [workflow_dispatch]

jobs:
  test-unity-project:
    name: Test Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-GameFeelLab-WebGL
          restore-keys: |
            Library-GameFeelLab-
            Library-
      - name: Test Unity Project
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # to use GitHub Status Check
      - name: Upload Unity Test Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test result
          path: artifacts