name: Unity Minimum Viable CI/CD

on: [workflow_dispatch]

jobs:
  build-unity-project:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-GameFeelLab-StandaloneWindows64
          restore-keys: |
            Library-GameFeelLab-
            Library-
      - name: Build Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildMethod: CliffLeeCL.ProjectBuilder.BuildProject
          customParameters: -outputPath artifacts -defineSymbolConfig Debug
      - name: Upload Unity Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GameFeelLab-StandaloneWindows64
          path: artifacts